///////////////////////////////////////////////////////////
//  BaseWSUIAttribute.cs
//  Implementation of the Class BaseWSUIAttribute
//  Generated by Enterprise Architect
//  Created on:      27-Sep-2013 1:14:51 AM
//  Original author: Yariki
///////////////////////////////////////////////////////////

using System;
using WSUI.Core.Interfaces;

namespace WSUI.Core.Core.Attributes
{
    public class BaseWSUIAttribute : Attribute, IWSUIAttribute
    {
        public BaseWSUIAttribute()
        {
        }

        ~BaseWSUIAttribute()
        {
        }

        public virtual void Dispose()
        {
        }
    }//end BaseWSUIAttribute
}//end namespace Attributes