///////////////////////////////////////////////////////////
//  BaseOFAttribute.cs
//  Implementation of the Class BaseOFAttribute
//  Generated by Enterprise Architect
//  Created on:      27-Sep-2013 1:14:51 AM
//  Original author: Yariki
///////////////////////////////////////////////////////////

using System;
using OF.Core.Interfaces;

namespace OF.Core.Core.Attributes
{
    public class BaseOFAttribute : Attribute, IOFAttribute
    {
        public BaseOFAttribute()
        {
        }

        ~BaseOFAttribute()
        {
        }

        public virtual void Dispose()
        {
        }
    }//end BaseOFAttribute
}//end namespace Attributes