///////////////////////////////////////////////////////////
//  IFieldCash.cs
//  Implementation of the Interface IFieldCash
//  Generated by Enterprise Architect
//  Created on:      29-Sep-2013 9:40:39 PM
//  Original author: Yariki
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;

namespace OF.Core.Interfaces
{
    public interface IFieldCash
    {
        /// <param name="type"></param>
        /// <param name="exludeIngnored"></param>
        IList<Tuple<string, string, int, bool>> GetFields(Type type);

        IEnumerable<string> GetIgnoredFields(Type type);

        void Initialize();
    } //end IFieldCash
} //end namespace Interfaces