///////////////////////////////////////////////////////////
//  IResultMessage.cs
//  Implementation of the Interface IResultMessage
//  Generated by Enterprise Architect
//  Created on:      28-Sep-2013 2:31:57 PM
//  Original author: Yariki
///////////////////////////////////////////////////////////

namespace OF.Core.Interfaces
{
    public interface IResultMessage
    {
        string Message { get; set; }
    }//end IResultMessage
}//end namespace Interfaces