///////////////////////////////////////////////////////////
//  IRuleQueryGenerator.cs
//  Implementation of the Interface IRuleQueryGenerator
//  Generated by Enterprise Architect
//  Created on:      29-Sep-2013 10:48:56 AM
//  Original author: Yariki
///////////////////////////////////////////////////////////

using System.Collections.Generic;
using OF.Core.Core.Rules;

namespace OF.Core.Interfaces
{
    public interface IRuleQueryGenerator
    {
        ///
        /// <param name="listCriteriaRules"></param>
        string GenerateWherePart(IList<IRule> listCriteriaRules);

        string GenerateAdvancedWherePart();
    }//end IRuleQueryGenerator
}//end namespace Interfaces