///////////////////////////////////////////////////////////
//  ISearchRule.cs
//  Implementation of the Interface ISearchRule
//  Generated by Enterprise Architect
//  Created on:      27-Sep-2013 10:55:09 PM
//  Original author: Yariki
///////////////////////////////////////////////////////////




namespace WSUI.Core.Interfaces 
{

	public interface ISearchTemplateRule<T> where T : class 
	{

		ISearchResult<T> GetResults();

	}//end ISearchTemplateRule

}//end namespace Interfaces