///////////////////////////////////////////////////////////
//  ISearchResult.cs
//  Implementation of the Interface ISearchResult
//  Generated by Enterprise Architect
//  Created on:      28-Sep-2013 2:32:18 PM
//  Original author: Yariki
///////////////////////////////////////////////////////////


using System.Collections.Generic;
using WSUI.Core.Enums;
namespace WSUI.Core.Interfaces 
{
	public interface ISearchResult  
    {
		TypeResult Type{ get; } 
		IList<IResultMessage> Messages{ get; } 
		IList<ISearchObject> OperationResult{ get; } 
		
	}//end ISearchResult

}//end namespace Interfaces