///////////////////////////////////////////////////////////
//  ISearchRule.cs
//  Implementation of the Interface ISearchRule
//  Generated by Enterprise Architect
//  Created on:      27-Sep-2013 10:55:09 PM
//  Original author: Yariki
///////////////////////////////////////////////////////////

namespace WSUI.Core.Interfaces
{
    public interface ISearchRule
    {
        ISearchResult GetResults();
    }//end ISearchTemplateRule
}//end namespace Interfaces