///////////////////////////////////////////////////////////
//  ISystemSearchResult.cs
//  Implementation of the Interface ISystemSearchResult
//  Generated by Enterprise Architect
//  Created on:      28-Sep-2013 3:27:21 PM
//  Original author: Yariki
///////////////////////////////////////////////////////////


using System.Collections.Generic;
using WSUI.Core.Data;
namespace WSUI.Core.Interfaces 
{
	public interface ISystemSearchResult   
    {
	    int Priority{get;}
	    IList<BaseSearchObject> Result {get;}
	}//end ISystemSearchResult

}//end namespace Interfaces