///////////////////////////////////////////////////////////
//  IOFAttribute.cs
//  Implementation of the Interface IOFAttribute
//  Generated by Enterprise Architect
//  Created on:      27-Sep-2013 1:14:31 AM
//  Original author: Yariki
///////////////////////////////////////////////////////////

namespace OF.Core.Interfaces
{
    public interface IOFAttribute
    {
    }//end IOFAttribute
}//end namespace Interfaces