///////////////////////////////////////////////////////////
//  IWSUIAttribute.cs
//  Implementation of the Interface IWSUIAttribute
//  Generated by Enterprise Architect
//  Created on:      27-Sep-2013 1:14:31 AM
//  Original author: Yariki
///////////////////////////////////////////////////////////

namespace WSUI.Core.Interfaces
{
    public interface IWSUIAttribute
    {
    }//end IWSUIAttribute
}//end namespace Interfaces