///////////////////////////////////////////////////////////
//  AttachmentFilenameSearchRule.cs
//  Implementation of the Class AttachmentFilenameSearchRule
//  Generated by Enterprise Architect
//  Created on:      29-Sep-2013 10:41:43 AM
//  Original author: Yariki
///////////////////////////////////////////////////////////




using WSUI.Core.Core.Search;
using WSUI.Core.Data;

namespace WSUI.Infrastructure.Implements.Rules 
{
	public class AttachmentFilenameSearchRule : BaseSearchRule<AttachmentSearchObject>
	{

		public AttachmentFilenameSearchRule()
        {

		}


	}//end AttachmentFilenameSearchRule

}//end namespace Implements