///////////////////////////////////////////////////////////
//  BaseFilelSearchRule.cs
//  Implementation of the Class BaseFilelSearchRule
//  Generated by Enterprise Architect
//  Created on:      03-Oct-2013 8:53:03 PM
//  Original author: Yariki
///////////////////////////////////////////////////////////




using WSUI.Core.Core.Search;
using WSUI.Core.Data;

namespace WSUI.Infrastructure.Implements.Rules 
{
	public class BaseFilelSearchRule : BaseSearchRule<FileSearchObject> 
    {

		public BaseFilelSearchRule()
        {

		}


	}//end BaseFilelSearchRule

}//end namespace Implements