///////////////////////////////////////////////////////////
//  ContactSearchRule.cs
//  Implementation of the Class ContactSearchRule
//  Generated by Enterprise Architect
//  Created on:      29-Sep-2013 10:41:39 AM
//  Original author: Yariki
///////////////////////////////////////////////////////////


using System.Collections.Generic;
using System.Linq;
using System.Text;
using WSUI.Core.Core.Rules;
using WSUI.Core.Core.Search;
using WSUI.Core.Data;

namespace WSUI.Infrastructure.Implements.Rules 
{
	public class ContactSearchRule : BaseSearchRule<ContactSearchObject>
	{
        private const string WhereTemplate = 
            " WHERE System.Kind = 'contact' AND ";
	    private const string NamesTemplate =
	        "CONTAINS(System.Contact.FirstName,'\"{0}*\" OR \"*{0}*\"') OR CONTAINS(System.Contact.LastName,'\"{0}*\" OR \"*{0}*\"')";

	    private const string CollapseTemplate = "( {0} )";

		public ContactSearchRule()
		{
		    Priority = 1;
		}

	    protected override string OnGenerateWherePart(IList<IRule> listCriterisRules)
	    {
	        string result = string.Empty;
	        if (Query.IndexOf(' ') > -1)
	        {
	            result = WhereTemplate + ProcessAndBuildWhereQueryPart(Query);
	        }
	        else
	        {
	            result = WhereTemplate + string.Format(NamesTemplate, Query);
	        }
	        return result;
	    }

	    private string ProcessAndBuildWhereQueryPart(string query)
	    {
	        StringBuilder strBuid = new StringBuilder();
	        var arr = query.Split(' ').ToList();
	        strBuid.Append(string.Format(NamesTemplate, arr[0]));
	        foreach (var item in arr.Skip(1))
	        {
	            strBuid.Append(" AND " + string.Format(NamesTemplate, item));
	        }
	        return string.Format(CollapseTemplate, strBuid.ToString());
	    }

        public override void Init()
        {
            RuleName = "Contact";
            CountFirstProcess = 100;
            CountSecondProcess = 50;
            base.Init();
        }

	}//end ContactSearchRule

}//end namespace Implements