///////////////////////////////////////////////////////////
//  EmailContentSearchRule.cs
//  Implementation of the Class EmailContentSearchRule
//  Generated by Enterprise Architect
//  Created on:      29-Sep-2013 10:41:46 AM
//  Original author: Yariki
///////////////////////////////////////////////////////////


using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using WSUI.Core.Core.Rules;
using WSUI.Core.Data.ElasticSearch;
using WSUI.Infrastructure.Implements.Rules.BaseRules;

namespace WSUI.Infrastructure.Implements.Rules 
{
	public class EmailContentSearchRule : BaseEmailSearchRule 
    {
        private string WhereTemplate =
            "WHERE CONTAINS(System.Kind,'email') AND System.Message.DateReceived < '{0}' AND CONTAINS(*,{1},1033) ORDER BY System.Message.DateReceived DESC";//System.Search.Contents


		public EmailContentSearchRule()
		{
		    Priority = 3;
		}

        public EmailContentSearchRule(object lockObject)
        :base(lockObject)
        {
            Priority = 3;
        }

	    public override void Init()
	    {
            RuleName = "EmailContent";
	        base.Init();
	    }

	    protected override Expression<Func<WSUIEmail, string>> GetSearchedProperty()
	    {
	        return e => e.Content;
	    }
    }//end EmailContentSearchRule

}//end namespace Implements