///////////////////////////////////////////////////////////
//  EmailContentSearchRule.cs
//  Implementation of the Class EmailContentSearchRule
//  Generated by Enterprise Architect
//  Created on:      29-Sep-2013 10:41:46 AM
//  Original author: Yariki
///////////////////////////////////////////////////////////


using System.Collections.Generic;
using WSUI.Core.Core.Rules;

namespace WSUI.Infrastructure.Implements.Rules 
{
	public class EmailContentSearchRule : BaseEmailSearchRule 
    {
        private string WhereTemplate =
            "WHERE System.Kind = 'email' AND System.Message.DateReceived < '{0}' AND CONTAINS(System.Search.Contents,{1}) ORDER BY System.Message.DateReceived DESC";//System.Search.Contents


		public EmailContentSearchRule()
		{
		    Priority = 3;
		}

	    protected override string OnGenerateWherePart(IList<IRule> listCriterisRules)
	    {
            var dateString = FormatDate(ref LastDate);
            var and = GetProcessingSearchCriteria(listCriterisRules).Item1;
            return string.Format(WhereTemplate, dateString, and);
	    }

	    public override void Init()
	    {
            RuleName = "EmailContent";
	        base.Init();
	    }
    }//end EmailContentSearchRule

}//end namespace Implements