///////////////////////////////////////////////////////////
//  EmailSubjectSearchRule.cs
//  Implementation of the Class EmailSubjectSearchRule
//  Generated by Enterprise Architect
//  Created on:      29-Sep-2013 10:41:48 AM
//  Original author: Yariki
///////////////////////////////////////////////////////////


using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using Microsoft.Practices.Unity;
using Nest;
using OF.Core.Core.AdvancedSearchCriteria;
using OF.Core.Core.Rules;
using OF.Core.Data.ElasticSearch;
using OF.Core.Data.ElasticSearch.Request;
using OF.Core.Data.ElasticSearch.Request.Email;
using OF.Core.Enums;
using OF.Core.Extensions;
using OF.Infrastructure.Implements.Rules.BaseRules;

namespace OF.Infrastructure.Implements.Rules
{
    public class EmailSubjectSearchRule : BaseEmailSearchRule
    {

        public EmailSubjectSearchRule(IUnityContainer container)
            :this(null,container)
        {
            Priority = 2;
        }

        public EmailSubjectSearchRule(object lockObject, IUnityContainer container)
            : base(lockObject,container)
        {
            Priority = 2;
        }

        protected override bool GetIncludedInAdvancedMode()
        {
            return true;
        }

        public override void Init()
        {
            RuleName = "EmailSubject";
            base.Init();
        }

        protected override Expression<Func<OFEmail, string>> GetSearchedProperty()
        {
            return e => e.Subject;
        }


        protected override OFBody GetSearchBody()
        {
            var preparedCriterias = GetKeywordsList();
            var body = new OFBodySort();
            body.sort = new OFSortDateCreated();
            if (preparedCriterias.Count > 1)
            {
                var query = new OFQueryBoolMust<OFTerm<OFSimpleSubjectTerm>>();
                body.query = query;
                foreach (var preparedCriteria in preparedCriterias)
                {
                    var term = new OFTerm<OFSimpleSubjectTerm>(preparedCriteria);
                    query._bool.must.Add(term);
                }
                return body;
            }
            body.query = new OFQuerySimpleTerm<OFSimpleSubjectTerm>(Query);
            return body;
        }

        protected override IFieldSort BuildAdvancedFieldSortSortSelector(SortFieldDescriptor<OFEmail> sortFieldDescriptor)
        {
            if (AdvancedSearchCriterias.IsNull() ||
               AdvancedSearchCriterias.All(c => c.CriteriaType != AdvancedSearchCriteriaType.SortBy))
                return sortFieldDescriptor.OnField(e => e.Datereceived);

            var sortingCriteria = AdvancedSearchCriterias.First(c => c.CriteriaType == AdvancedSearchCriteriaType.SortBy);
            var sort = (AdvancedSearchSortByType)sortingCriteria.Value;
            switch (sort)
            {
                case AdvancedSearchSortByType.NewestToOldest:
                    return  sortFieldDescriptor.OnField(e => e.Datereceived).Descending();
                case AdvancedSearchSortByType.OldestToNewest:
                    return sortFieldDescriptor.OnField(e => e.Datereceived).Ascending();
                default:
                    return sortFieldDescriptor.OnField(e => e.Datereceived);
            }
        }

        protected override QueryContainer BuildAdvancedQuery(QueryDescriptor<OFEmail> queryDescriptor)
        {
            if (AdvancedSearchCriterias.IsEmpty())
            {
                return new QueryContainer();
            }
            var listCriterias = new List<Func<QueryDescriptor<OFEmail>, QueryContainer>>();
            foreach (var advancedSearchCriteria in AdvancedSearchCriterias)
            {
                if (advancedSearchCriteria.Value.IsNull() || advancedSearchCriteria.Value.IsStringEmptyOrNull())
                    continue;
                var temp = advancedSearchCriteria;
                switch (temp.CriteriaType)
                {
                    case AdvancedSearchCriteriaType.To:
                        var listShould = new List<Func<QueryDescriptor<OFEmail>, QueryContainer>>();
                        listShould.Add(d => d.Term("to.address",temp.Value));
                        listShould.Add(d => d.Term("to.name", temp.Value));

                        listCriterias.Add(desc => desc.Bool(bd => bd.Should(listShould.ToArray())));

                        break;
                    case AdvancedSearchCriteriaType.Folder:
                        listCriterias.Add(d => d.Term(e => e.Folder, temp.Value));
                        break;
                    case AdvancedSearchCriteriaType.Body:
                        listCriterias.Add(d => d.Term(e => e.Analyzedcontent,temp.Value));
                        break;
                }
            }
            return queryDescriptor.Bool(bd => bd.Must(listCriterias.ToArray()));
        }
    }//end EmailSubjectSearchRule

}//end namespace Implements