///////////////////////////////////////////////////////////
//  FileContentSearchRule.cs
//  Implementation of the Class FileContentSearchRule
//  Generated by Enterprise Architect
//  Created on:      29-Sep-2013 10:41:49 AM
//  Original author: Yariki
///////////////////////////////////////////////////////////


using Microsoft.Office.Interop.Outlook;

namespace WSUI.Infrastructure.Implements.Rules 
{
	public class FileContentSearchRule : BaseFilelSearchRule 
    {

		public FileContentSearchRule()
		{
		    Priority = 5;
            WhereTemplate = " WHERE System.Kind <> 'email' AND System.Kind <> 'folder' AND System.Kind <> 'contact' AND Contains(System.Search.Contents,{0},1033) AND System.DateCreated < '{1}' ORDER BY System.DateCreated DESC";
		}

	    public override void Init()
	    {
            RuleName = "FileContent";
	        base.Init();
	    }
    }//end FileContentSearchRule

}//end namespace Implements