///////////////////////////////////////////////////////////
//  FileFilenameSearchRule.cs
//  Implementation of the Class FileFilenameSearchRule
//  Generated by Enterprise Architect
//  Created on:      29-Sep-2013 10:41:50 AM
//  Original author: Yariki
///////////////////////////////////////////////////////////





namespace WSUI.Infrastructure.Implements.Rules 
{
	public class FileFilenameSearchRule : BaseFilelSearchRule 
    {

		public FileFilenameSearchRule()
        {

		}

	}//end FileFilenameSearchRule

}//end namespace Implements