///////////////////////////////////////////////////////////
//  FileFilenameSearchRule.cs
//  Implementation of the Class FileFilenameSearchRule
//  Generated by Enterprise Architect
//  Created on:      29-Sep-2013 10:41:50 AM
//  Original author: Yariki
///////////////////////////////////////////////////////////


namespace WSUI.Infrastructure.Implements.Rules 
{
	public class FileFilenameSearchRule : BaseFilelSearchRule
	{

		public FileFilenameSearchRule()
		{
		    Priority = 4;
            WhereTemplate = " WHERE Contains(System.Kind,'NOT \"email\"') AND Contains(System.Kind,'NOT \"folder\"') AND Contains(System.Kind,'NOT \"contact\"') AND Contains(System.ItemUrl,{0},1033) AND System.DateCreated < '{1}' ORDER BY System.DateCreated DESC";
		}//System.Kind <> 'email' AND System.Kind <> 'folder' AND System.Kind <> 'contact' AND

	    public override void Init()
	    {
	        RuleName = "FileFilename";
	        base.Init();
	    }
	}//end FileFilenameSearchRule

}//end namespace Implements