///////////////////////////////////////////////////////////
//  FileContentSearchRule.cs
//  Implementation of the Class FileContentSearchRule
//  Generated by Enterprise Architect
//  Created on:      29-Sep-2013 10:41:49 AM
//  Original author: Yariki
///////////////////////////////////////////////////////////


using OF.Infrastructure.Implements.Rules.BaseRules;

namespace OF.Infrastructure.Implements.Rules 
{
	public class FileContentSearchRule : BaseFileSearchRule 
    {

		public FileContentSearchRule()
		{
		    ConstructorInit();
		}

        public FileContentSearchRule(object lockObject)
            :base(lockObject)
        {
            ConstructorInit();
        }


	    private void ConstructorInit()
	    {
	        Priority = 5;
	    }

//System.Kind <> 'email' AND System.Kind <> 'folder' AND System.Kind <> 'contact' AND




	    public override void Init()
	    {
            RuleName = "FileContent";
	        base.Init();
	    }
    }//end FileContentSearchRule

}//end namespace Implements