///////////////////////////////////////////////////////////
//  ContactSearchRule.cs
//  Implementation of the Class ContactSearchRule
//  Generated by Enterprise Architect
//  Created on:      29-Sep-2013 10:41:39 AM
//  Original author: Yariki
///////////////////////////////////////////////////////////


using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.Practices.Unity;
using Nest;
using OF.Core.Core.Rules;
using OF.Core.Core.Search;
using OF.Core.Data;
using OF.Core.Data.ElasticSearch;
using OF.Core.Data.ElasticSearch.Request;
using OF.Core.Data.ElasticSearch.Request.Base;
using OF.Core.Data.ElasticSearch.Request.Contact;
using OF.Core.Data.ElasticSearch.Request.Contact.MatchPhrase;
using OF.Core.Enums;
using OF.Core.Interfaces;

namespace OF.Infrastructure.Implements.Rules 
{
	public class OFContactSearchRule : BaseSearchRule<OFContactSearchObject,OFContact>
	{
        public OFContactSearchRule(IUnityContainer container)
            :this(null,container)
		{
		    Priority = 1;
		}

        public OFContactSearchRule(object lockObject, IUnityContainer container)
        :base(lockObject,false,container)
        {
            Priority = 1;
        }
        
        public override void Init()
        {
            RuleName = "Contact";
            CountFirstProcess = 100;
            CountSecondProcess = 50;
            ObjectType = RuleObjectType.Contact;
            base.Init();
        }

	    protected override bool NeedSorting
	    {
	        get { return false; }
	    }

	    protected override OFBody GetSearchBody()
	    {
            var preparedCriterias = GetKeywordsList();
	        var body = new OFBody();
            
            if (preparedCriterias.Count > 1)
            {

                var queries = new OFQueryBoolConditions();
                body.query = queries;
                foreach (var preparedCriteria in preparedCriterias)
                {

                    var should = new OFQueryBoolShould<IOFQueryMatchPhrase<OFBaseMatchPhrase>>();

                    var fn = new OFQueryMatchPhrase<OFContactFirstNameMatchPhrase>(new OFContactFirstNameMatchPhrase() {firstname = preparedCriteria.Result});
                    var ln = new OFQueryMatchPhrase<OFContactLastNameMatchPhrase>(new OFContactLastNameMatchPhrase() {lastname = preparedCriteria.Result });
                    var ea11 = new OFQueryMatchPhrase<OFContactEmailaddress1MatchPhrase>(new OFContactEmailaddress1MatchPhrase() {emailaddress1 = preparedCriteria.Result});
                    var ea22 = new OFQueryMatchPhrase<OFContactEmailaddress2MatchPhrase>(new OFContactEmailaddress2MatchPhrase() {emailaddress2 = preparedCriteria.Result}) ;
                    var ea33 = new OFQueryMatchPhrase<OFContactEmailaddress3MatchPhrase>(new OFContactEmailaddress3MatchPhrase() {emailaddress3 = preparedCriteria.Result});

                    should._bool.should.Add(fn);
                    should._bool.should.Add(ln);
                    should._bool.should.Add(ea11);
                    should._bool.should.Add(ea22);
                    should._bool.should.Add(ea33);

                    var must = new OFMustCondition<object>(){Value = should};

                    queries._bool.Add(must);
                }
                return body;
            }
            var query = new OFQueryBoolShould<IOFQueryMatchPhrase<OFBaseMatchPhrase>>();
            body.query = query;

            var firstName = new OFQueryMatchPhrase<OFContactFirstNameMatchPhrase>(new OFContactFirstNameMatchPhrase() { firstname = Query });
            var lastName = new OFQueryMatchPhrase<OFContactLastNameMatchPhrase>(new OFContactLastNameMatchPhrase() { lastname = Query });
            var ea1 = new OFQueryMatchPhrase<OFContactEmailaddress1MatchPhrase>(new OFContactEmailaddress1MatchPhrase() { emailaddress1 = Query });
            var ea2 = new OFQueryMatchPhrase<OFContactEmailaddress2MatchPhrase>(new OFContactEmailaddress2MatchPhrase() { emailaddress2 = Query });
            var ea3 = new OFQueryMatchPhrase<OFContactEmailaddress3MatchPhrase>(new OFContactEmailaddress3MatchPhrase() { emailaddress3 = Query });

            query._bool.should.Add(firstName);
            query._bool.should.Add(lastName);
            query._bool.should.Add(ea1);
            query._bool.should.Add(ea2);
            query._bool.should.Add(ea3);
	        return body;
	    }

	    protected override OFBody GetAlternativeSearchBody()
	    {
            var preparedCriterias = GetKeywordsList();
            var body = new OFBody();

            if (preparedCriterias.Count > 1)
            {

                var queries = new OFQueryBoolConditions();
                body.query = queries;
                foreach (var preparedCriteria in preparedCriterias)
                {

                    var should = new OFQueryBoolShould<IOFWildcard<OFBaseWildcard>>();

                    var fn = new OFWildcard<OFFirstNameWildcard>(preparedCriteria.Result);
                    var ln = new OFWildcard<OFLastNameWildcard>(preparedCriteria.Result);
                    var ea11 = new OFWildcard<OFEmailaddress1Wildcard>(preparedCriteria.Result);
                    var ea22 = new OFWildcard<OFEmailaddress2Wildcard>(preparedCriteria.Result);
                    var ea33 = new OFWildcard<OFEmailaddress3Wildcard>(preparedCriteria.Result);

                    should._bool.should.Add(fn);
                    should._bool.should.Add(ln);
                    should._bool.should.Add(ea11);
                    should._bool.should.Add(ea22);
                    should._bool.should.Add(ea33);

                    var must = new OFMustCondition<object>() { Value = should };

                    queries._bool.Add(must);
                }
                return body;
            }
            var query = new OFQueryBoolShould<IOFWildcard<OFBaseWildcard>>();
            body.query = query;

            var firstName = new OFWildcard<OFFirstNameWildcard>(Query);
            var lastName = new OFWildcard<OFLastNameWildcard>(Query);
            var ea1 = new OFWildcard<OFEmailaddress1Wildcard>(Query);
            var ea2 = new OFWildcard<OFEmailaddress2Wildcard>(Query);
            var ea3 = new OFWildcard<OFEmailaddress3Wildcard>(Query);

            query._bool.should.Add(firstName);
            query._bool.should.Add(lastName);
            query._bool.should.Add(ea1);
            query._bool.should.Add(ea2);
            query._bool.should.Add(ea3);
            return body;
        }
    }//end ContactSearchRule

}//end namespace Implements