///////////////////////////////////////////////////////////
//  ContactSearchRule.cs
//  Implementation of the Class ContactSearchRule
//  Generated by Enterprise Architect
//  Created on:      29-Sep-2013 10:41:39 AM
//  Original author: Yariki
///////////////////////////////////////////////////////////


using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.Practices.Unity;
using Nest;
using OF.Core.Core.Rules;
using OF.Core.Core.Search;
using OF.Core.Data;
using OF.Core.Data.ElasticSearch;
using OF.Core.Data.ElasticSearch.Request;
using OF.Core.Data.ElasticSearch.Request.Base;
using OF.Core.Data.ElasticSearch.Request.Contact;
using OF.Core.Enums;
using OF.Core.Interfaces;

namespace OF.Infrastructure.Implements.Rules 
{
	public class OFContactSearchRule : BaseSearchRule<OFContactSearchObject,OFContact>
	{
        public OFContactSearchRule(IUnityContainer container)
            :this(null,container)
		{
		    Priority = 1;
		}

        public OFContactSearchRule(object lockObject, IUnityContainer container)
        :base(lockObject,false,container)
        {
            Priority = 1;
        }
        
        public override void Init()
        {
            RuleName = "Contact";
            CountFirstProcess = 100;
            CountSecondProcess = 50;
            ObjectType = RuleObjectType.Contact;
            base.Init();
        }

	    protected override bool NeedSorting
	    {
	        get { return false; }
	    }

	    protected override OFBody GetSearchBody()
	    {
            var preparedCriterias = GetKeywordsList();
	        var body = new OFBody();
            
            if (preparedCriterias.Count > 1)
            {

                var queries = new OFQueryBoolConditions();
                body.query = queries;
                foreach (var preparedCriteria in preparedCriterias)
                {

                    var should = new OFQueryBoolShould<OFBaseTerm>();

                    var fn = new OFFirstNameTerm();
                    fn.SetValue(preparedCriteria.Result);

                    var ln = new OFLastNameTerm();
                    ln.SetValue(preparedCriteria.Result);
                    var ea11 = new OFEmailaddress1Term();
                    ea11.SetValue(preparedCriteria.Result);
                    var ea22 = new OFEmailaddress2Term();
                    ea22.SetValue(preparedCriteria.Result);
                    var ea33 = new OFEmailaddress3Term();
                    ea33.SetValue(preparedCriteria.Result);

                    should._bool.should.Add(fn);
                    should._bool.should.Add(ln);
                    should._bool.should.Add(ea11);
                    should._bool.should.Add(ea22);
                    should._bool.should.Add(ea33);

                    var must = new OFMustCondition<object>(){Value = should};

                    queries._bool.Add(must);
                }
                return body;
            }
            var query = new OFQueryBoolShould<OFBaseTerm>();
            body.query = query;
            var firstName = new OFFirstNameTerm();
            firstName.SetValue(Query);
	        var lastName = new OFLastNameTerm();
            lastName.SetValue(Query);
	        var ea1 = new OFEmailaddress1Term();
            ea1.SetValue(Query);
            var ea2 = new OFEmailaddress2Term();
            ea2.SetValue(Query);
            var ea3 = new OFEmailaddress3Term();
            ea3.SetValue(Query);
            query._bool.should.Add(firstName);
            query._bool.should.Add(lastName);
            query._bool.should.Add(ea1);
            query._bool.should.Add(ea2);
            query._bool.should.Add(ea3);
	        return body;
	    }

	    protected override OFBody GetAlternativeSearchBody()
	    {
            var preparedCriterias = GetKeywordsList();
            var body = new OFBody();

            if (preparedCriterias.Count > 1)
            {

                var queries = new OFQueryBoolConditions();
                body.query = queries;
                foreach (var preparedCriteria in preparedCriterias)
                {

                    var should = new OFQueryBoolShould<IOFWildcard<OFBaseWildcard>>();

                    var fn = new OFWildcard<OFFirstNameWildcard>(preparedCriteria.Result);
                    var ln = new OFWildcard<OFLastNameWildcard>(preparedCriteria.Result);
                    var ea11 = new OFWildcard<OFEmailaddress1Wildcard>(preparedCriteria.Result);
                    var ea22 = new OFWildcard<OFEmailaddress2Wildcard>(preparedCriteria.Result);
                    var ea33 = new OFWildcard<OFEmailaddress3Wildcard>(preparedCriteria.Result);

                    should._bool.should.Add(fn);
                    should._bool.should.Add(ln);
                    should._bool.should.Add(ea11);
                    should._bool.should.Add(ea22);
                    should._bool.should.Add(ea33);

                    var must = new OFMustCondition<object>() { Value = should };

                    queries._bool.Add(must);
                }
                return body;
            }
            var query = new OFQueryBoolShould<IOFWildcard<OFBaseWildcard>>();
            body.query = query;

            var firstName = new OFWildcard<OFFirstNameWildcard>(Query);
            var lastName = new OFWildcard<OFLastNameWildcard>(Query);
            var ea1 = new OFWildcard<OFEmailaddress1Wildcard>(Query);
            var ea2 = new OFWildcard<OFEmailaddress2Wildcard>(Query);
            var ea3 = new OFWildcard<OFEmailaddress3Wildcard>(Query);

            query._bool.should.Add(firstName);
            query._bool.should.Add(lastName);
            query._bool.should.Add(ea1);
            query._bool.should.Add(ea2);
            query._bool.should.Add(ea3);
            return body;
        }
    }//end ContactSearchRule

}//end namespace Implements