///////////////////////////////////////////////////////////
//  EmailContentSearchRule.cs
//  Implementation of the Class EmailContentSearchRule
//  Generated by Enterprise Architect
//  Created on:      29-Sep-2013 10:41:46 AM
//  Original author: Yariki
///////////////////////////////////////////////////////////


using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using Microsoft.Practices.Unity;
using OF.Core.Core.Rules;
using OF.Core.Data.ElasticSearch;
using OF.Core.Data.ElasticSearch.Request;
using OF.Core.Data.ElasticSearch.Request.Email;
using OF.Core.Enums;
using OF.Infrastructure.Implements.Rules.BaseRules;

namespace OF.Infrastructure.Implements.Rules 
{
	public class OFEmailContentSearchRule : OFBaseEmailSearchRule 
    {

        public OFEmailContentSearchRule(IUnityContainer container)
            :this(null,container)
		{
		    Priority = 3;
		}

        public OFEmailContentSearchRule(object lockObject, IUnityContainer container)
        :base(lockObject,container)
        {
            Priority = 3;
        }

	    public override void Init()
	    {
            RuleName = "EmailContent";
	        base.Init();
	    }

        protected override OFBody GetSearchBody()
        {
            var preparedCriterias = GetKeywordsList();
            var body = new OFBodySort();
            body.sort = new OFSortDateCreated();
            if (preparedCriterias.Count > 1)
            {
                var query = new OFQueryBoolMust<OFTerm<OFSimpleContentTerm>>();
                body.query = query;
                foreach (var preparedCriteria in preparedCriterias)
                {
                    var term = new OFTerm<OFSimpleContentTerm>(preparedCriteria.Result);
                    query._bool.must.Add(term);
                }
                return body;
            }
            if (preparedCriterias.All(p => p.Type == ofRuleType.Quote))
            {
                var criteria = preparedCriterias.FirstOrDefault(p => p.Type == ofRuleType.Quote);
                body.query = new OFQueryMatchPhrase<OFContentMatchPhrase>(new OFContentMatchPhrase() { analyzedcontent = criteria.Result });
                return body;
            }
            body.query = new OFWildcard<OFAnalyzedContentWildcard>(Query);
            return body;
        }

	    protected override Expression<Func<OFEmail, string>> GetSearchedProperty()
	    {
	        return e => e.Analyzedcontent;
	    }
    }//end EmailContentSearchRule

}//end namespace Implements