///////////////////////////////////////////////////////////
//  TypeResult.cs
//  Implementation of the Class TypeResult
//  Generated by Enterprise Architect
//  Created on:      28-Sep-2013 2:31:48 PM
//  Original author: Yariki
///////////////////////////////////////////////////////////

namespace OF.Core.Enums
{
    public enum TypeResult : int
    {
        None,
        Ok,
        Error
    }//end TypeResult
}//end namespace Enums