///////////////////////////////////////////////////////////
//  AllSearchSystem.cs
//  Implementation of the Class AllSearchSystem
//  Generated by Enterprise Architect
//  Created on:      29-Sep-2013 10:41:41 AM
//  Original author: Yariki
///////////////////////////////////////////////////////////




using WSUI.Core.Core.Search;
namespace WSUI.Infrastructure.Implements.Systems 
{
	public class AllSearchSystem : BaseSearchSystem 
    {

		public AllSearchSystem()
        {

		}

	}//end AllSearchSystem

}//end namespace Implements