///////////////////////////////////////////////////////////
//  AttachmentSearchSystem.cs
//  Implementation of the Class AttachmentSearchSystem
//  Generated by Enterprise Architect
//  Created on:      29-Sep-2013 10:41:44 AM
//  Original author: Yariki
///////////////////////////////////////////////////////////


using Microsoft.Practices.Unity;
using OF.Core.Core.Search;
using OF.Infrastructure.Implements.Rules;

namespace OF.Infrastructure.Implements.Systems 
{
	public class AttachmentSearchSystem : BaseSearchSystem 
    {

		public AttachmentSearchSystem()
        {

		}

        public override void Init(IUnityContainer container)
	    {
            AddRule(new AttachmentFilenameSearchRule(container));
            AddRule(new AttachmentContentSearchRule(container));
	        base.Init(container);
	    }
    }//end AttachmentSearchSystem

}//end namespace Implements