///////////////////////////////////////////////////////////
//  AttachmentSearchSystem.cs
//  Implementation of the Class AttachmentSearchSystem
//  Generated by Enterprise Architect
//  Created on:      29-Sep-2013 10:41:44 AM
//  Original author: Yariki
///////////////////////////////////////////////////////////




using OF.Core.Core.Search;
using OF.Infrastructure.Implements.Rules;

namespace OF.Infrastructure.Implements.Systems 
{
	public class AttachmentSearchSystem : BaseSearchSystem 
    {

		public AttachmentSearchSystem()
        {

		}

	    public override void Init()
	    {
            //AddRule(new FileFilenameSearchRule());
            //AddRule(new FileContentSearchRule());
            AddRule(new AttachmentFilenameSearchRule());
            AddRule(new AttachmentContentSearchRule());
	        base.Init();
	    }
    }//end AttachmentSearchSystem

}//end namespace Implements