///////////////////////////////////////////////////////////
//  EmailSearchSystem.cs
//  Implementation of the Class EmailSearchSystem
//  Generated by Enterprise Architect
//  Created on:      29-Sep-2013 10:41:47 AM
//  Original author: Yariki
///////////////////////////////////////////////////////////


using WSUI.Core.Core.Search;
using WSUI.Infrastructure.Implements.Rules;

namespace WSUI.Infrastructure.Implements.Systems 
{
	public class EmailSearchSystem : BaseSearchSystem 
    {
		public EmailSearchSystem()
        {
		}

	    public override void Init()
	    {
            AddRule(new EmailSubjectSearchRule());
            AddRule(new EmailContentSearchRule());
	        base.Init();
	    }


    }//end EmailSearchSystem

}//end namespace Implements