///////////////////////////////////////////////////////////
//  AttachmentFilenameSearchRule.cs
//  Implementation of the Class AttachmentFilenameSearchRule
//  Generated by Enterprise Architect
//  Created on:      29-Sep-2013 10:41:43 AM
//  Original author: Yariki
///////////////////////////////////////////////////////////


using System.Collections.Generic;
using System.Linq;
using System.Text;
using WSUI.Core.Core.Rules;
using WSUI.Core.Core.Search;
using WSUI.Core.Data;
using WSUI.Core.Data.ElasticSearch;
using WSUI.Core.Enums;
using WSUI.Core.Logger;
using WSUI.Core.Utils;
using WSUI.Infrastructure.Service.Helpers;

namespace WSUI.Infrastructure.Implements.Rules.BaseRules 
{
	public class BaseAttachmentSearchRule : BaseSearchRule<AttachmentSearchObject,WSUIStub>
	{
        protected const string WhereTemplate = "WHERE Contains(System.ItemUrl,'\"at=*\"') AND System.DateModified < '{0}'  AND ( {1} ) ORDER BY System.DateModified DESC";

		public BaseAttachmentSearchRule()
            :base(null,true)
		{
		    
		}

        public BaseAttachmentSearchRule(object lockOject)
            :base(lockOject,true)
        {
            
        }

        protected virtual string GetSearchProperty()
        {
            return "*"; // searching in all property
        }

	    protected override string OnGenerateWherePart(IList<IRule> listCriterisRules)
	    {
	        var dateString = FormatDate(ref LastDate);
	        var tuple = GetProcessingSearchCriteria(listCriterisRules);
	        string addCriteria = GetAdditionalCriteria(tuple.Item2);
	        return string.Format(WhereTemplate, dateString, addCriteria);
	    }

        protected override System.Data.DataTable GetDataTable(string query)
        {
            var listIgnored = FieldCash.Instance.GetIgnoredFields(typeof (AttachmentSearchObject));
            return IndexerDataReader.Instance.GetDataByReader(query,listIgnored);
        }

	    private string GetAdditionalCriteria(List<string> listWord)
	    {
            if (listWord.Count == 0)
                 return string.Empty;
             var temp = new StringBuilder();

             temp.Append(string.Format("Contains({0},'\"{1}\"') ", GetSearchProperty(), listWord[0]));// System.ItemUrl

             if (listWord.Count > 1)
                 for (int i = 1; i < listWord.Count; i++)
                     temp.Append(string.Format("AND Contains({0},'\"{1}\"') ", GetSearchProperty(), listWord.ElementAt(i)));

             return temp.ToString();
	    }

	    public override void Init()
	    {
            InitCounts();
            ObjectType = RuleObjectType.File;
	        base.Init();
	    }

        protected virtual void InitCounts()
        {
            CountFirstProcess = 50;
            CountSecondProcess = 20;
        }

        protected override void ProcessCountAdded()
	    {
            lock(InternalLock)
                CountAdded = Result.GroupBy(i => new { Name = i.ItemNameDisplay, Size = i.Size }).Count();
            if (CountAdded == CountProcess)
                IsInterupt = true;
	    }

	    protected override void ProcessResult()
	    {
            var groups = GetSortedAttachmentSearchObjects(Result).GroupBy(i => new { Name = i.ItemNameDisplay, Size = i.Size });
	        var result = new List<AttachmentSearchObject>();
            WSSqlLogger.Instance.LogInfo(string.Format("Count attachments: {0}", groups.Count()));
            foreach (var group in groups)
            {
                var item = group.FirstOrDefault();
                //TypeSearchItem type = SearchItemHelper.GetTypeItem(item.ItemUrl, item.Kind != null && item.Kind.Length > 0 ? item.Kind[0].ToString() : string.Empty);
                //foreach (var attachmentSearchObject in group.Skip(1))
                //{
                //    item.AddItem(attachmentSearchObject);
                //}
                result.Add(item);
            }
            Result.Clear();
            if (result.Count > 0)
            {
                WSSqlLogger.Instance.LogInfo("{0}: {1}",RuleName,result.Count);
                Result = result;
                LastDate = Result.Min(d => d.DateReceived);
            }
	    }

	    protected virtual IEnumerable<AttachmentSearchObject> GetSortedAttachmentSearchObjects(IEnumerable<AttachmentSearchObject> list)
	    {
	        return list.OrderByDescending(d => d.DateReceived);
	    }

	}//end AttachmentFilenameSearchRule

}//end namespace Implements