///////////////////////////////////////////////////////////
//  AdressSearchObject.cs
//  Implementation of the Class AdressSearchObject
//  Generated by Enterprise Architect
//  Created on:      27-Sep-2013 1:33:32 AM
//  Original author: Yariki
///////////////////////////////////////////////////////////

using WSUI.Core.Core.Attributes;
namespace WSUI.Core.Data 
{
	public class AdressSearchObject : BaseSearchObject 
    {
        [Field("System.Message.ToAddress", 7, false)]    
		public string ToAddress{ get;  set;}

        [Field("System.Message.FromAddress", 8, false)]
		public string FromAddress{ get;  set;}

        [Field("System.Message.CcAddress", 9, false)]
		public string CcAddress{ get;  set;} 

		public AdressSearchObject()
        {
		}

	}//end AdressSearchObject

}//end namespace Data