///////////////////////////////////////////////////////////
//  AttachmentSearchObject.cs
//  Implementation of the Class AttachmentSearchObject
//  Generated by Enterprise Architect
//  Created on:      27-Sep-2013 1:33:31 AM
//  Original author: Yariki
///////////////////////////////////////////////////////////


using System;
using WSUI.Core.Data;
namespace WSUI.Core.Data {
	public class AttachmentSearchObject : BaseEmailSearchObject {

		public DateTime DateModified{ get;  set;} 

		public AttachmentSearchObject(){

		}

		~AttachmentSearchObject(){

		}

	}//end AttachmentSearchObject

}//end namespace Data