///////////////////////////////////////////////////////////
//  BaseSearchObject.cs
//  Implementation of the Class BaseSearchObject
//  Generated by Enterprise Architect
//  Created on:      27-Sep-2013 1:33:26 AM
//  Original author: Yariki
///////////////////////////////////////////////////////////


using System;

namespace WSUI.Core.Data {
	public class BaseSearchObject {

		public string ItemName{ get;  set;} 
		public string ItemUrl{ get;  set;} 
		public string[] Kind{ get;  set;} 
		public DateTime DateCreated{ get;  set;} 
		public string ItemNameDisplay{ get;  set;} 
		public int Size{ get;  set;} 

		public BaseSearchObject(){

		}

		~BaseSearchObject(){

		}

	}//end BaseSearchObject

}//end namespace Data