///////////////////////////////////////////////////////////
//  BaseEmailSearchObject.cs
//  Implementation of the Class BaseEmailSearchObject
//  Generated by Enterprise Architect
//  Created on:      27-Sep-2013 1:33:39 AM
//  Original author: Yariki
///////////////////////////////////////////////////////////

using System;
using System.Globalization;
using OF.Core.Core.Attributes;
using OF.Core.Data.ElasticSearch;
using OF.Core.Extensions;
using OF.Core.Helpers;

namespace OF.Core.Data
{
    public class BaseEmailSearchObject : BaseSearchObject
    {
        #region [needs]

        private string _fromEmailName = string.Empty;

        #endregion [needs]


        public string ConversationId
        {
            get { return Get(() => ConversationId); }
            set { Set(() => ConversationId,value);}
        }

        public string OutlookConversationId
        {
            get { return Get(() => OutlookConversationId); }
            set { Set(() => OutlookConversationId, value); }
        }

        public string FolderMessageStoreIdPart
        {
            get { return Get(() => FolderMessageStoreIdPart); }
            set { Set(() => FolderMessageStoreIdPart, value); }
        }

        public string StorageName
        {
            get { return Get(() => StorageName); }
            set { Set(() => StorageName, value); }
        }

        public string Folder
        {
            get { return Get(() => Folder); }
            set { Set(() => Folder, value); }
        }


        public OFRecipient[] To
        {
            get { return Get(() => To); }
            set { Set(() => To, value);}
        }

        public OFRecipient[] Cc
        {
            get { return Get(() => Cc); }
            set { Set(() => Cc, value); }
        }

        public OFRecipient[] Bcc
        {
            get { return Get(() => Bcc); }
            set { Set(() => Bcc, value); }
        }

        public DateTime DateReceived
        {
            get { return Get(() => DateReceived); }
            set { Set(() => DateReceived,value);}
        }

        public string ConversationIndex
        {
            get { return Get(() => ConversationIndex); }
            set { Set(() => ConversationIndex,value);}
        }

        public string FromAddress
        {
            get { return Get(() => FromAddress); }
            set { Set(() => FromAddress,value);}
        }

        public string FromName
        {
            get { return Get(() => FromName); }
            set { Set(() => FromName,value);}
        }

        public OFAttachment[] Attachments
        {
            get { return Get(() => Attachments); }
            set { Set(() => Attachments, value); }
        }

        public string HasAttachments
        {
            get
            {
                return Get(() => HasAttachments);
            }
        }

        public bool IsAttachmentPresent
        {
            get { return bool.Parse(HasAttachments); }
        }

        public string From
        {
            get
            {
                if (string.IsNullOrEmpty(_fromEmailName))
                {
                    _fromEmailName = GetEmailOrName(FromAddress, FromName);
                }
                return _fromEmailName;
            }
        }

        public BaseEmailSearchObject()
        {
        }

        private string GetEmailOrName(string address, string name)
        {
            
            return !string.IsNullOrEmpty(address) && IsEmail(address) ? address : name;
        }

        private bool IsEmail(string email)
        {
            return email.IsEmail();
        }

        public bool IsOst
        {
            get { return string.IsNullOrWhiteSpace(StorageName); }
        }

        protected string[] CheckValidType(object val)
        {
            if (val != null && val.GetType().IsArray)
            {
                return val as string[];
            }
            return new string[] { val as string };
        }
    }//end BaseEmailSearchObject
}//end namespace Data