///////////////////////////////////////////////////////////
//  BaseEmailSearchObject.cs
//  Implementation of the Class BaseEmailSearchObject
//  Generated by Enterprise Architect
//  Created on:      27-Sep-2013 1:33:39 AM
//  Original author: Yariki
///////////////////////////////////////////////////////////


using System;
using WSUI.Core.Data;
namespace WSUI.Core.Data {
	public class BaseEmailSearchObject : BaseSearchObject {

		public string ConversationId{ get;  set;} 
		public string ToAdress{ get;  set;} 
		public DateTime DateReceived{ get;  set;} 

		public BaseEmailSearchObject(){

		}

		~BaseEmailSearchObject(){

		}

	}//end BaseEmailSearchObject

}//end namespace Data