///////////////////////////////////////////////////////////
//  EmailSearchObject.cs
//  Implementation of the Class EmailSearchObject
//  Generated by Enterprise Architect
//  Created on:      27-Sep-2013 1:33:36 AM
//  Original author: Yariki
///////////////////////////////////////////////////////////

using WSUI.Core.Core.Attributes;
using WSUI.Core.Enums;

namespace WSUI.Core.Data
{
    public class EmailSearchObject : BaseEmailSearchObject
    {
        public string Subject { get; set; }

        public EmailSearchObject()
        {
            TypeItem = TypeSearchItem.Email;
        }

    }//end EmailSearchObject
}//end namespace Data