///////////////////////////////////////////////////////////
//  FileSearchObject.cs
//  Implementation of the Class FileSearchObject
//  Generated by Enterprise Architect
//  Created on:      27-Sep-2013 1:33:38 AM
//  Original author: Yariki
///////////////////////////////////////////////////////////




using WSUI.Core.Data;
namespace WSUI.Core.Data {
	public class FileSearchObject : BaseSearchObject {

		public FileSearchObject(){

		}

	}//end FileSearchObject

}//end namespace Data