///////////////////////////////////////////////////////////
//  AttachmentSearchObject.cs
//  Implementation of the Class AttachmentSearchObject
//  Generated by Enterprise Architect
//  Created on:      27-Sep-2013 1:33:31 AM
//  Original author: Yariki
///////////////////////////////////////////////////////////

using System;
using System.Globalization;
using OF.Core.Core.Attributes;
using OF.Core.Enums;

namespace OF.Core.Data
{
    public class OFAttachmentSearchObject : OFBaseEmailSearchObject
    {
        public DateTime DateModified { get; set; }

        public OFAttachmentSearchObject()
        {
            TypeItem = OFTypeSearchItem.Attachment;
        }

    }//end AttachmentSearchObject
}//end namespace Data