///////////////////////////////////////////////////////////
//  ContactSearchObject.cs
//  Implementation of the Class ContactSearchObject
//  Generated by Enterprise Architect
//  Created on:      27-Sep-2013 1:33:34 AM
//  Original author: Yariki
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Windows;
using OF.Core.Core.Attributes;
using OF.Core.Core.MVVM;
using OF.Core.Enums;
using OF.Core.Interfaces;

namespace OF.Core.Data
{
    public class OFContactSearchObject : OFBaseSearchObject
    {

        public OFContactSearchObject()
        {
            TypeItem = OFTypeSearchItem.Contact;
            Tag = "Click for details";
        }

        public string FirstName
        {
            get { return Get(() => FirstName); }
            set { Set(() => LastName, value); }
        }

        public string LastName
        {
            get { return Get(() => LastName); }
            set { Set(() => LastName, value); }
        }

        public string EmailAddress1
        {
            get { return Get(() => EmailAddress1); }
            set { Set(() => EmailAddress1, value); }
        }

        public string EmailAddress2
        {
            get { return Get(() => EmailAddress2); }
            set { Set(() => EmailAddress2, value); }
        }

        public string EmailAddress3
        {
            get { return Get(() => EmailAddress3); }
            set { Set(() => EmailAddress3, value); }
        }

        public string BusinessTelephone
        {
            get { return Get(() => BusinessTelephone); }
            set { Set(() => BusinessTelephone, value); }
        }

        public string HomeTelephone
        {
            get { return Get(() => HomeTelephone); }
            set { Set(() => HomeTelephone, value); }
        }

        public string MobileTelephone
        {
            get { return Get(() => MobileTelephone); }
            set { Set(() => MobileTelephone, value); }
        }

        public string HomeAddressCity
        {
            get { return Get(() => HomeAddressCity); }
            set { Set(() => HomeAddressCity, value); }
        }

        public string HomeAddressCountry
        {
            get { return Get(() => HomeAddressCountry); }
            set { Set(() => HomeAddressCountry, value); }
        }

        public string HomeAddressPostalCode
        {
            get { return Get(() => HomeAddressPostalCode); }
            set { Set(() => HomeAddressPostalCode, value); }
        }

        public string HomeAddressState
        {
            get { return Get(() => HomeAddressState); }
            set { Set(() => HomeAddressState, value); }
        }

        public string HomeAddressStreet
        {
            get { return Get(() => HomeAddressStreet); }
            set { Set(() => HomeAddressStreet, value); }
        }

        public string HomeAddressPostOfficeBox
        {
            get { return Get(() => HomeAddressPostOfficeBox); }
            set { Set(() => HomeAddressPostOfficeBox, value); }
        }

        public string BusinessAddressCity
        {
            get { return Get(() => BusinessAddressCity); }
            set { Set(() => BusinessAddressCity, value); }
        }

        public string BusinessAddressCountry
        {
            get { return Get(() => BusinessAddressCountry); }
            set { Set(() => BusinessAddressCountry, value); }
        }

        public string BusinessAddressState
        {
            get { return Get(() => BusinessAddressState); }
            set { Set(() => BusinessAddressState, value); }
        }

        public string BusinessAddressStreet
        {
            get { return Get(() => BusinessAddressStreet); }
            set { Set(() => BusinessAddressStreet, value); }
        }

        public string BusinessAddressPostOfficeBox
        {
            get { return Get(() => BusinessAddressPostOfficeBox); }
            set { Set(() => BusinessAddressPostOfficeBox, value); }
        }

        public string Keyword
        {
            get { return Get(() => Keyword); }
            set { Set(() => Keyword, value); }
        }

        public string Location
        {
            get { return Get(() => Location); }
            set { Set(() => Location, value); }
        }

        public string CompanyName
        {
            get { return Get(() => CompanyName); }
            set { Set(() => CompanyName, value); }
        }

        public string Title
        {
            get { return Get(() => Title); }
            set { Set(() => Title, value); }
        }

        public string DepartmentName
        {
            get { return Get(() => DepartmentName); }
            set { Set(() => DepartmentName, value); }
        }

        public string MiddleName
        {
            get { return Get(() => MiddleName); }
            set { Set(() => MiddleName, value); }
        }

        public string DisplayNamePrefix
        {
            get { return Get(() => DisplayNamePrefix); }
            set { Set(() => DisplayNamePrefix, value); }
        }

        public string Profession
        {
            get { return Get(() => Profession); }
            set { Set(() => Profession, value); }
        }

        public string Note
        {
            get { return Get(() => Note); }
            set { Set(() => Note, value); }
        }

        public string HomeAddress
        {
            get { return Get(() => HomeAddress); }
            set { Set(() => HomeAddress, value); }
        }


        public string WorkAddress
        {
            get { return Get(() => WorkAddress); }
            set { Set(() => WorkAddress, value); }
        }

        public string OtherAddress
        {
            get { return Get(() => OtherAddress); }
            set { Set(() => OtherAddress, value); }
        }

        public DateTime Birthday
        {
            get { return Get(() => Birthday); }
            set { Set(() => Birthday, value); }
        }

        public string AddressType
        {
            get { return Get(() => AddressType); }
            set { Set(() => AddressType, value); }
        }

       

        public string GetEmail()
        {
            return !string.IsNullOrEmpty(EmailAddress1)
                ? EmailAddress1
                : !string.IsNullOrEmpty(EmailAddress2)
                    ? EmailAddress2
                    : !string.IsNullOrEmpty(EmailAddress3)
                        ? EmailAddress3
                        : string.Empty;
        }


        public override string ToString()
        {
            return string.Format("{0} {1}; {2}; {3}; {4}", this.FirstName, this.LastName, this.EmailAddress1, this.EmailAddress2, this.EmailAddress3);
        }

    }//end ContactSearchObject
}//end namespace Data