///////////////////////////////////////////////////////////
//  EmailSearchObject.cs
//  Implementation of the Class EmailSearchObject
//  Generated by Enterprise Architect
//  Created on:      27-Sep-2013 1:33:36 AM
//  Original author: Yariki
///////////////////////////////////////////////////////////

using System;
using System.Text;
using OF.Core.Core.Attributes;
using OF.Core.Enums;
using OF.Core.Extensions;

namespace OF.Core.Data
{
    public class OFEmailSearchObject : OFBaseEmailSearchObject
    {
        public string Subject
        {
            get { return Get(() => Subject); }
            set { Set(() => Subject,value);}
        }

        public string Content
        {
            get { return Get(() => Content); }
            set { Set(() => Content, value); }
        }

        public string HtmlContent
        {
            get { return Get(() => HtmlContent); }
            set { Set(() => HtmlContent, value); }
        }

        public string GetContent()
        {
            var content = !HtmlContent.IsStringEmptyOrNull()
                ? Encoding.UTF8.GetString(Convert.FromBase64String(HtmlContent))
                : !Content.IsStringEmptyOrNull()
                    ? Encoding.UTF8.GetString(Convert.FromBase64String(Content))
                    : "";
            return content;
        }


        public OFEmailSearchObject()
        {
            TypeItem = OFTypeSearchItem.Email;
        }

    }//end EmailSearchObject
}//end namespace Data