///////////////////////////////////////////////////////////
//  EmailSearchObject.cs
//  Implementation of the Class EmailSearchObject
//  Generated by Enterprise Architect
//  Created on:      27-Sep-2013 1:33:36 AM
//  Original author: Yariki
///////////////////////////////////////////////////////////

using OF.Core.Core.Attributes;
using OF.Core.Enums;

namespace OF.Core.Data
{
    public class OFEmailSearchObject : OFBaseEmailSearchObject
    {
        public string Subject
        {
            get { return Get(() => Subject); }
            set { Set(() => Subject,value);}
        }

        public string Content
        {
            get { return Get(() => Content); }
            set { Set(() => Content, value); }
        }

        public string HtmlContent
        {
            get { return Get(() => HtmlContent); }
            set { Set(() => HtmlContent, value); }
        }

        public OFEmailSearchObject()
        {
            TypeItem = OFTypeSearchItem.Email;
        }

    }//end EmailSearchObject
}//end namespace Data