///////////////////////////////////////////////////////////
//  FileSearchObject.cs
//  Implementation of the Class FileSearchObject
//  Generated by Enterprise Architect
//  Created on:      27-Sep-2013 1:33:38 AM
//  Original author: Yariki
///////////////////////////////////////////////////////////

namespace OF.Core.Data
{
    public class OFFileSearchObject : OFBaseSearchObject
    {
        public OFFileSearchObject()
        {
        }
    }//end FileSearchObject
}//end namespace Data