///////////////////////////////////////////////////////////
//  QueryGenerator.cs
//  Implementation of the Class QueryGenerator
//  Generated by Enterprise Architect
//  Created on:      28-Sep-2013 1:56:28 PM
//  Original author: Yariki
///////////////////////////////////////////////////////////




using WSUI.Core.Interfaces;
namespace WSUI.Core.Utils {
	public class QueryGenerator : IQueryGenerator 
	{

		
		protected QueryGenerator()
		{

		}

		private static Lazy<IQueryGenerator> _instance = new Lazy<IQueryGenerator>(() => {
																							var inst = new QueryGenerator();
																							inst.Init();
																							return inst;
																							});
		
		public static IQueryGenerator Instance 
		{
			get{return _instance.Value;}
		}
		
		/// 
		/// <param name="type"></param>
		/// <param name="searchCriteria"></param>
		/// <param name="exludeIgnored"></param>
		public string GenerateQuery(Type type, string searchCriteria,int topResult, IRuleQueryGenerator ruleQueryGenerator, bool exludeIgnored)
		{

			return "";
		}

		private void Init()
		{}
		
		private Tuple<string,int> GetFieldsList(Type type, bool exludeIgnoread)
		{
		}
		
		private string GenerateSelectPart(IList<Tuple,int> list, int top)
		{}
		
		private string GenerateFromPart()
		{}
		
		private string GenerateWherePart(IRuleQueryGenerator ruleQueryGenerator)
		{}
		
		
	}//end QueryGenerator

}//end namespace Utils