///////////////////////////////////////////////////////////
//  BaseSearchSystem.cs
//  Implementation of the Class BaseSearchSystem
//  Generated by Enterprise Architect
//  Created on:      28-Sep-2013 3:55:40 PM
//  Original author: Yariki
///////////////////////////////////////////////////////////


using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using WSUI.Core.Interfaces;
using WSUI.Core.Extensions;
using WSUI.Core.Logger;

namespace WSUI.Core.Core.Search 
{
	public abstract class BaseSearchSystem : ISearchSystem 
    {

		private Thread _mainSearchThread;
		private IList<ISearch> _listRules;
	    private volatile bool _needStop = false;

	    protected IList<ISystemSearchResult> InternalResult;
	    protected volatile bool IsSearching = false;

		protected BaseSearchSystem()
        {
            _listRules = new List<ISearch>();
            InternalResult = new List<ISystemSearchResult>();
		}

		public virtual void Init()
		{
		    IsSearching = false;
            _listRules.ForEach(item => item.Init());
		}

		public virtual void Reset()
        {
            InternalResult.Clear();
		    IsSearching = false;
		    _needStop = false;
            _listRules.ForEach(item => item.Reset());
        }

		/// 
		/// <param name="searchCriteris"></param>
		public void SetSearchCriteria(string searchCriteris)
		{
		    _listRules.ForEach(item => item.SetSearchCriteria(searchCriteris));
		}

		public virtual void Search()
		{
		    if (IsSearching)
		        return;
            InitBeforeSearch();
            _mainSearchThread = new Thread(DoSearch){Priority = ThreadPriority.Highest};
            _mainSearchThread.Start();
            RaiseSearchStarted();
		}

		public virtual void Stop()
		{
		    _needStop = true;
            _listRules.ForEach(item => item.Stop());
            RaiseSearchStopped();
		}

		public event Action<object> SearchStarted;

		public event Action<object> SearchFinished;

		public event Action<object> SearchStoped;

		public IList<ISystemSearchResult> GetResult()
        {
			return InternalResult;
		}

		protected virtual void RaiseSearchStarted()
		{
		    var temp = SearchStarted;
		    if (temp != null)
		        temp(null);
		}

		protected virtual void RaiseSearchFinished()
		{
		    var temp = SearchFinished;
		    if (temp != null)
		        temp(null);
		}

		protected virtual void RaiseSearchStopped()
		{
		    var temp = SearchStoped;
		    if (temp != null)
		        temp(null);
		}

		protected virtual void ProcessData()
        {

		}

		protected IList<ISearch> GetRules()
        {
			return _listRules;
		}

		protected virtual void DoSearch()
		{
		    try
		    {
		        var listEvents = new List<AutoResetEvent>();
                _listRules.ForEach(item =>
                {
                    if (!item.IsSearching)
                    {
                        listEvents.Add(item.GetEvent());
                        item.Search();
                    }
                });
		        WaitHandle.WaitAll(listEvents.ToArray());
                WSSqlLogger.Instance.LogError("+++++++++++++++++ searching is DONE!!!!+++++++++++++++");
		        if (_needStop)
		        {
		            RaiseSearchStopped();
		            IsSearching = false;
                    WSSqlLogger.Instance.LogError("Searching was stoped");
                    return;
		        }
		        foreach (var item in _listRules.OrderBy(i => i.Priority))
		        {
		            var result = (item as ISearchRule).GetResults();
		            if (result == null)
		                continue;
		            var itemResult = new SystemSearchResult(item.Priority, result.OperationResult);
		            InternalResult.Add(itemResult);
		        }
		    }
		    catch (Exception ex)
		    {
                WSSqlLogger.Instance.LogError("{0}",ex.Message);
		    }
		    finally
		    {
		        IsSearching = false;
                RaiseSearchFinished();
		    }
		}

	    protected void AddRule(ISearch rule)
	    {
	        if (rule == null)
	            return;
            _listRules.Add(rule);
	    }

	    protected virtual void InitBeforeSearch()
	    {
            if(InternalResult.Count > 0)
	            InternalResult.Clear(); 
	    }

	}//end BaseSearchSystem

}//end namespace Search