///////////////////////////////////////////////////////////
//  SearchResult.cs
//  Implementation of the Class SearchResult
//  Generated by Enterprise Architect
//  Created on:      28-Sep-2013 2:45:03 PM
//  Original author: Yariki
///////////////////////////////////////////////////////////

using System.Collections.Generic;
using OF.Core.Enums;
using OF.Core.Interfaces;

namespace OF.Core.Core.Search
{
    public class OFSearchResult : ISearchResult
    {
        public OFSearchResult(OFTypeResult type, IList<IResultMessage> messages, IEnumerable<ISearchObject> result)
        {
            Type = type;
            Messages = messages;
            OperationResult = new List<ISearchObject>(result); ;
        }

        public OFTypeResult Type { get; private set; }

        public IList<IResultMessage> Messages { get; private set; }

        public IList<ISearchObject> OperationResult { get; private set; }
    }//end SearchResult
}//end namespace Search