///////////////////////////////////////////////////////////
//  SystemSearchResult.cs
//  Implementation of the Class SystemSearchResult
//  Generated by Enterprise Architect
//  Created on:      28-Sep-2013 3:27:41 PM
//  Original author: Yariki
///////////////////////////////////////////////////////////

using OF.Core.Enums;
using OF.Core.Interfaces;

namespace OF.Core.Core.Search
{
    public class OFSystemSearchResult : ISystemSearchResult
    {
        public OFSystemSearchResult(int priority, ISearchResult result,
            RuleObjectType objectType)
        {
            Priority = priority;
            Result = result;
            ObjectType = objectType;
        }

        public int Priority
        {
            get;
            private set;
        }

        public ISearchResult Result
        {
            get;
            private set;
        }

        public RuleObjectType ObjectType { get; private set; }
    }//end SystemSearchResult
}//end namespace Search