///////////////////////////////////////////////////////////
//  ResultMessage.cs
//  Implementation of the Class ResultMessage
//  Generated by Enterprise Architect
//  Created on:      28-Sep-2013 2:32:07 PM
//  Original author: Yariki
///////////////////////////////////////////////////////////

using OF.Core.Interfaces;

namespace OF.Core.Core.Search
{
    public class ResultMessage : IResultMessage
    {
        public ResultMessage()
        {
        }

        public string Message { get; set; }
    }//end ResultMessage
}//end namespace Search