///////////////////////////////////////////////////////////
//  SearchResult.cs
//  Implementation of the Class SearchResult
//  Generated by Enterprise Architect
//  Created on:      28-Sep-2013 2:45:03 PM
//  Original author: Yariki
///////////////////////////////////////////////////////////


using System.Collections.Generic;
using WSUI.Core.Enums;
using WSUI.Core.Interfaces;
namespace WSUI.Core.Core.Search 
{
	public class SearchResult<T> : ISearchResult<T>  where T : class
    {

		public SearchResult(TypeResult type,IList<IResultMessage> messages, IList<T> result)
        {
			Type  = type;
			Messages = messages;
			OperationResult = result;
		}

		public TypeResult Type{get; private set;}
		public IList<IResultMessage> Messages{get; private set;}
		public IList<T> OperationResult{get; private set;}

	}//end SearchResult

}//end namespace Search