///////////////////////////////////////////////////////////
//  SystemSearchResult.cs
//  Implementation of the Class SystemSearchResult
//  Generated by Enterprise Architect
//  Created on:      28-Sep-2013 3:27:41 PM
//  Original author: Yariki
///////////////////////////////////////////////////////////




using WSUI.Core.Interfaces;
namespace WSUI.Core.Core.Search 
{
	public class SystemSearchResult : ISystemSearchResult 
    {

        public SystemSearchResult(int priority, System.Collections.Generic.IList<ISearchObject> result)
		{
		    Priority = priority;
            Result = result;
		}

        public int Priority
        {
            get;
            private set;
        }

        public System.Collections.Generic.IList<ISearchObject> Result
        {
            get;
            private set;
        }
    }//end SystemSearchResult

}//end namespace Search