///////////////////////////////////////////////////////////
//  ContactSearchSystem.cs
//  Implementation of the Class ContactSearchSystem
//  Generated by Enterprise Architect
//  Created on:      29-Sep-2013 10:41:45 AM
//  Original author: Yariki
///////////////////////////////////////////////////////////




using WSUI.Core.Core.Search;
namespace WSUI.Infrastructure.Implements {
	public class ContactSearchSystem : BaseSearchSystem {

		public ContactSearchSystem(){

		}

	}//end ContactSearchSystem

}//end namespace Implements