///////////////////////////////////////////////////////////
//  ContactSearchRule.cs
//  Implementation of the Class ContactSearchRule
//  Generated by Enterprise Architect
//  Created on:      29-Sep-2013 10:41:39 AM
//  Original author: Yariki
///////////////////////////////////////////////////////////




using WSUI.Core.Core.Search;
using WSUI.Core.Data;

namespace WSUI.Infrastructure.Implements {
	public class ContactSearchRule : BaseSearchRule<ContactSearchObject>
	{

		public ContactSearchRule(){

		}


	}//end ContactSearchRule

}//end namespace Implements