///////////////////////////////////////////////////////////
//  EmailSearchSystem.cs
//  Implementation of the Class EmailSearchSystem
//  Generated by Enterprise Architect
//  Created on:      29-Sep-2013 10:41:47 AM
//  Original author: Yariki
///////////////////////////////////////////////////////////




using WSUI.Core.Core.Search;
namespace WSUI.Infrastructure.Implements {
	public class EmailSearchSystem : BaseSearchSystem {

		public EmailSearchSystem(){

		}


	}//end EmailSearchSystem

}//end namespace Implements