///////////////////////////////////////////////////////////
//  EmailContentSearchRule.cs
//  Implementation of the Class EmailContentSearchRule
//  Generated by Enterprise Architect
//  Created on:      29-Sep-2013 10:41:46 AM
//  Original author: Yariki
///////////////////////////////////////////////////////////




using WSUI.Core.Core.Search;
using WSUI.Core.Data;

namespace WSUI.Infrastructure.Implements {
	public class EmailContentSearchRule : BaseSearchRule<EmailSearchObject> {

		public EmailContentSearchRule(){

		}

	}//end EmailContentSearchRule

}//end namespace Implements