///////////////////////////////////////////////////////////
//  EmailSubjectSearchRule.cs
//  Implementation of the Class EmailSubjectSearchRule
//  Generated by Enterprise Architect
//  Created on:      29-Sep-2013 10:41:48 AM
//  Original author: Yariki
///////////////////////////////////////////////////////////




using WSUI.Core.Core.Search;
using WSUI.Core.Data;

namespace WSUI.Infrastructure.Implements {
	public class EmailSubjectSearchRule : BaseSearchRule<EmailSearchObject> {

		public EmailSubjectSearchRule(){

		}


	}//end EmailSubjectSearchRule

}//end namespace Implements