///////////////////////////////////////////////////////////
//  FileContentSearchRule.cs
//  Implementation of the Class FileContentSearchRule
//  Generated by Enterprise Architect
//  Created on:      29-Sep-2013 10:41:49 AM
//  Original author: Yariki
///////////////////////////////////////////////////////////




using WSUI.Core.Core.Search;
using WSUI.Core.Data;

namespace WSUI.Infrastructure.Implements {
	public class FileContentSearchRule : BaseFilelSearchRule {

		public FileContentSearchRule(){

		}


	}//end FileContentSearchRule

}//end namespace Implements